name: PR

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  composer-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: none
      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --prefer-dist
      - name: Run security audit
        run: composer audit -vvv
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: none
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=1G
  tests:
    needs: [phpstan, composer-audit]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, pdo, pdo_sqlite, sqlite3, xdebug
          coverage: xdebug
      - name: Copy .env
        run: cp .env.testing .env
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: Generate app key
        run: php artisan key:generate
      - name: Run migrations
        run: php artisan migrate --force
      - name: Run tests with coverage
        run: vendor/bin/phpunit --coverage-clover=coverage.xml --coverage-cobertura=coverage-cobertura.xml
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
      - name: Generate coverage summary
        id: coverage
        continue-on-error: true
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage-cobertura.xml
          badge: true
          format: markdown
          output: both
          fail_below_min: true
          thresholds: "80 90"
      - name: Post coverage comment on PR
        if: always() && github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md
      - name: Fail if coverage is below minimum
        if: steps.coverage.outcome == 'failure'
        run: |
          echo "Coverage is below the required 80% threshold."
          exit 1
